name: Demo

on:
  push:

permissions:
  contents: read

jobs:
  Demo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker Info
      run: |
        set -ex

        docker info
        docker versiond

    - name: Demo
      run: |
        set -ex

        cd debian10-7.3
        docker build -t test .
        docker run --rm test cat install.sh
        cd ..

        cd debian11-7.4
        docker build -t test .
        docker run --rm test cat install.sh
        cd ..

    - name: Stat
      run: |
        stat debian*/*
